C TEST-RULE: R705 R1155 R1157 6.3.3 15.6.2.4
C Fixed form, a continuation line, and uppercase new keywords.
      MODULE LANGUAGE_FIXED_FORM_M
      IMPLICIT NONE
      CONTAINS
      GENERIC FUNCTION FIXED_CODE(X) RESULT(N)
      TYPE(INTEGER,
     1 REAL), INTENT(IN) :: X
      INTEGER :: N
      SELECT GENERIC TYPE(X)
      DECLARED TYPE IS(INTEGER)
      N = 10 + X
      DECLARED TYPE IS(REAL)
      N = 20 + NINT(X)
      END SELECT
      END FUNCTION
      END MODULE

      PROGRAM LANGUAGE_FIXED_FORM_P
      USE LANGUAGE_FIXED_FORM_M
      IMPLICIT NONE
      IF (FIXED_CODE(3) .NE. 13) ERROR STOP 'FIXED INTEGER'
      IF (FIXED_CODE(4.0) .NE. 24) ERROR STOP 'FIXED REAL'
      END PROGRAM
